# -*- coding: utf-8 -*-
"""Monoalphabetic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pI_cpqxpZGN2_aNodsI9SHnRQwdCzRiP
"""

plaintext = input("Enter the plaintext here for the encryption!")
key = input("Enter the alphabets as a key for the encryption!")
cipher=""
for c in plaintext:
    if c in string.ascii_lowercase:
        index = ord(c)-ord('a')
        cipher = cipher + key[index]
    else:
        cipher = cipher + c
print("plaintext :"+ plaintext)
print("key"+ key)
print("ciphertext :"+ cipher)